# Generated by Django 4.1.2 on 2022-10-07 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_LOCALIDADES', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Boletins',
        ),
        migrations.AlterModelTable(
            name='localidades',
            table='localidades2',
        ),
    ]
