# Generated by Django 4.1.2 on 2022-10-07 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_LOCALIDADES', '0002_delete_boletins_alter_localidades_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='localidades',
            table='localidades',
        ),
    ]
